#!/usr/bin/env bash

set -euo pipefail

log()
{
    echo "$@" 1>&2
}

qemu=/home/user/.work/qemu/build/qemu-system-aarch64
sleep 1
log -------------------------------------------------------
$qemu --version
log -------------------------------------------------------
log "Connect to qemu monitor using: socat -,echo=0,icanon=0 unix-connect:qemu-monitor-socket"
log -------------------------------------------------------
args="$(echo $@)"
args="$(echo "$args" | sed -e 's/accel=kvm/accel=tcg/g' -e 's/,debug-threads=on//') -cpu cortex-a57 -monitor unix:$HOME/qemu-monitor-socket,server,nowait"
args="$args -smp $SMP,cores=$SMP,threads=1"
log "$qemu $(echo $args | tr ' ' '\n' | sed -e 's/$/ \\/')"
log -------------------------------------------------------
perf record -F 300 --call-graph fp -o ~/perf.data $qemu $args
log -------------------------------------------------------
