#!/usr/bin/env bash

set -euo pipefail

log()
{
    echo "$@"
}

script_dir=$(dirname $(readlink -f $0))
qemu_dir=$script_dir/qemu-9.1.0
qemu=$qemu_dir/qemu-system-x86_64
args="$@"
if [ "$(echo "$args" | grep version)" != "" ]; then
    $qemu -version
    exit 0
fi

log -------------------------------------------------------
$qemu --version
log -------------------------------------------------------
log "Connect to qemu monitor using: socat -,echo=0,icanon=0 unix-connect:qemu-monitor-socket"
log -------------------------------------------------------
args="$(echo "$args" | sed -e 's/accel=kvm/accel=tcg/g' | sed -e 's/,debug-threads=on//') -cpu max -monitor unix:$HOME/qemu-monitor-socket,server,nowait"
args="$args -smp $SMP,cores=$SMP,threads=1"
#args="$args -plugin $qemu_dir/tests/tcg/plugins/libbb.so -d plugin -D plugin.out"
log "$qemu $(echo $args | tr ' ' '\n' | sed -e 's/$/ \\/')"
log -------------------------------------------------------
/usr/bin/time -v perf record -F 300 --call-graph fp -o ~/perf.data $qemu $args
#cat plugin.out
log -------------------------------------------------------
